cars/urls.py
from django.contrib import admin
from django.urls import path

from carscat.views import CarsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', CarsView.as_view(), name='cars_list')
]

carscat/models.py
from django.db import models

# Create your models here.
from django.core.validators import MinValueValidator, MaxValueValidator

class Car(models.Model):
    T_CHOICES = (
        (1, 'Механика'),
        (2, 'Автомат'),
        (3, 'Робот'),
        (4, 'Вариатор'),
    )
    C_CHOICES = (
        (1, 'Чёрный'),
        (2, 'Белый'),
        (3, 'Красный'),
        (4, 'Оранжевый'),
        (5, 'Жёлтый'),
        (6, 'Зелёный'),
        (7, 'Голубой'),
        (8, 'Синий'),
        (9, 'Фиолетовый'),
        (10, 'Металик'),

    )

    vendor = models.CharField(max_length=50,
                              verbose_name='Производитель')
    model = models.CharField(max_length=50,
                             verbose_name='Модель авто')
    year = models.IntegerField(validators=[MinValueValidator(1900),
                                           MaxValueValidator(2020)],
                               verbose_name='Год выпуска')
    transmission = models.SmallIntegerField(choices=T_CHOICES,
                                            default=1,
                                            verbose_name='Коробка передач')
    color = models.SmallIntegerField(choices=C_CHOICES,
                                     verbose_name='Цвет',
                                     default=1)

    def __str__(self):
        return f'Автомобиль {self.model} марки {self.vendor}'

    class Meta:
        ordering = ('vendor', 'model',)

carscat/forms.py
from django import forms


class CarSearchForm(forms.Form):
    pass

carscat/views.py
from django.shortcuts import render

# Create your views here.
from functools import reduce
from operator import and_
from django.views.generic import ListView

# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Car


class CarsView(ListView):
    context_object_name = 'cars'
    # paginate_by = 10
    template_name = 'cars.html'

    def get_queryset(self):
        # Получить Querydict и преобразовать в dict
        query_dict = self.request.GET.dict()

        # Если есть фильтры в запросе
        if query_dict:
            # Инициализировать список фильтров
            # Год добавляется в любом случае
            query_filter = [Q(year__range=[int(query_dict['year_from']), int(query_dict['year_to'])])]

            # Если цвет != 'Все' добавить в фильтр цвет
            if query_dict['color'] != '0':
                query_filter.append(Q(color=int(query_dict['color'])))

            # Если тип КПП != 'Все' добавить в фильтр тип КПП
            if query_dict['transmission'] != '0':
                query_filter.append(Q(transmission=int(query_dict['transmission'])))

            # Если строка поиска не пустая, искать её в марке и производителе
            if query_dict['search']:
                query_filter.append(Q(vendor__icontains=query_dict['search']) |
                                    Q(model__icontains=query_dict['search']))

            # Сделать из списка фильтров фильтр для Q и создать queryset
            q_query = reduce(and_, (f for f in query_filter))
            queryset = Car.objects.filter(q_query)

            # print(query_filter)
            # print(q_query)
            # print(queryset.query)

        else:
            queryset = Car.objects.all()

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarsView, self).get_context_data(**kwargs)

        transmissions = {0: 'Тип КПП'}
        for t in Car.T_CHOICES:
            transmissions[t[0]] = t[1]

        colors = {0: 'Цвет'}
        for c in Car.C_CHOICES:
            colors[c[0]] = c[1]

        context['transmissions'] = transmissions
        context['colors'] = colors
        context['year_range'] = range(1900, 2021)
        context['query_dict'] = self.request.GET.dict()

        return context

carscat/templates/cars.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Каталог автомобилей</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
        crossorigin="anonymous">
  <style>
    .cart {
      margin-left: 10px;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
<div class="container">
<div class="row">
  <div class="col d-flex justify-content-center">
    <form action="{% url 'cars_list' %}" method="get" class="form-inline">
      <div class="form-group mb-2">
        <label for="year_from">Год выпуска от: </label>
      </div>
      <div class="form-group mb-2 mx-sm-3">
        <select name="year_from" id="year_from">
          {% for i in year_range %}
            <option value="{{ i }}">{{ i }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group mb-2">
        <label for="year_to">до: </label>
      </div>
      <div class="form-group mb-2 mx-sm-3">
        <select name="year_to" id="year_to">
          {% for i in year_range %}
            <option value="{{ i }}">{{ i }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group mb-2 mx-sm-3">
          <select name="color" id="color">
            {% for k, v in colors.items %}
              <option value="{{ k }}">{{ v }}</option>
            {% endfor %}
          </select>
        </div>
      <div class="form-group mb-2 mx-sm-3">
        <select name="transmission" id="transmission">
          {% for k, v in transmissions.items %}
            <option value="{{ k }}">{{ v }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group mb-2">
        <label for="search">Поиск: </label>
      </div>
      <div class="form-group mx-sm-3 mb-2">
        <input type="text" id="search" name="search" style="width: 80px" value="{{ query_dict.search }}">
      </div>
      <div class="form-group mx-sm-3 mb-2">
        <button type="submit" class="button btn-outline-primary">Искать</button>
      </div>
    </form>
  </div>
</div>
{#{% include "pagination.html" with page=page_obj %}#}
  <div class="row justify-content-center">
    <div class="col d-flex justify-content-center">
    <h6>Параметры запроса:
      Год от {{ query_dict.year_from }}
      до {{ query_dict.year_to }},
      цвет: {{ query_dict.color }},
      тип КПП: {{ query_dict.transmission }},
      строка запроса: "{{ query_dict.search }}"
    </h6>&nbsp;&nbsp;&nbsp;&nbsp;
    <h6><a href="{% url 'cars_list'%}">Сбросить фильтры</a> </h6>
    </div>
  </div>
  <div class="row">
    <div class="col d-flex flex-wrap justify-content-center car-cart">
      {% for car in cars %}
    <div class="cart border border-success" style="width: 20rem;">
      <div class="card-body">
        <h6 class="card-title">Модель: {{ car.model }}</h6>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Производитель: {{ car.vendor }}</li>
            <li class="list-group-item">Год выпуска: {{ car.year }}</li>
            <li class="list-group-item">Трансмиссия: {{ car.get_transmission_display }}</li>
            <li class="list-group-item">Цвет: {{ car.get_color_display }}</li>
          </ul>
      </div>
    </div>
  {% endfor %}
    </div>
  </div>
{#{% include "pagination.html" with page=page_obj %}#}
</div>
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
      let yearToElem = document.getElementById('year_to');

      {% if query_dict.year_to %}
        yearToElem.value = '{{ query_dict.year_to }}';
      {% else %}
        yearToElem.value = '2020';
      {% endif %}

      {% if query_dict.year_from %}
        let yearFromElem = document.getElementById('year_from');
        yearFromElem.value = '{{ query_dict.year_from }}';
      {% endif %}

      {% if query_dict.color %}
        let colorElem = document.getElementById('color');
        colorElem.value = '{{ query_dict.color }}';
      {% endif %}

      {% if query_dict.color %}
        let transElem = document.getElementById('transmission');
        transElem.value = '{{ query_dict.transmission }}';
      {% endif %}
});
</script>
</body>
</html>

carscat/templates/pagination.html
<div class="row justify-content-center">
    <div class="col-4 d-flex justify-content-center">
        <ul class="pagination">
            {% if page.has_previous %}
              <li class="page-item">
                <a href="?page={{ page.previous_page_number }}">Назад</a>
              </li>
            {% endif %}
          &nbsp;<li class="page-item">
            <a href="{% url 'cars_list' %}">В начало (без фильтров)</a>
          </li>
            {% if page.has_next %}
              <li class="page-item">
                <a href="?page={{ page.next_page_number }}">Вперёд</a>
              </li>
            {% endif %}
        </ul>
    </div>
  </div>